pipeline {
    agent any  // Use 'any' if you want to run on any available agent
    stages {
        stage('Build') {
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                echo 'Building inside Docker...'
            }
        }
    }
}

